package simpleTaskManager;

import javax.swing.JList;
import javax.swing.JOptionPane;

public class TaskListDisplayMenu extends javax.swing.JFrame {

	final private TaskListManager taskManager; 

	public TaskListDisplayMenu(TaskListManager taskManager) {
      this.taskManager = taskManager;
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jScrollPane1 = new javax.swing.JScrollPane();
      jList1 = new javax.swing.JList();
      jScrollPane2 = new javax.swing.JScrollPane();
      jList2 = new javax.swing.JList();
      jScrollPane3 = new javax.swing.JScrollPane();
      jList3 = new javax.swing.JList();
      jLabel1 = new javax.swing.JLabel();
      jLabel2 = new javax.swing.JLabel();
      jLabel3 = new javax.swing.JLabel();
      jMenuBar1 = new javax.swing.JMenuBar();
      jMenu1 = new javax.swing.JMenu();
      jMenu2 = new javax.swing.JMenu();
      jMenu3 = new javax.swing.JMenu();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
      setTitle("Simple Task Manager");

      jList1.setModel(new javax.swing.AbstractListModel() {
         String[] strings = taskManager.getTaskList(TaskStatus.IN_PROGRESS);
         public int getSize() { return strings.length; }
         public Object getElementAt(int i) { return strings[i]; }
      });
      jList1.addFocusListener(new java.awt.event.FocusAdapter() {
         public void focusGained(java.awt.event.FocusEvent evt) {
            jList1FocusGained(evt);
         }
      });
      jScrollPane1.setViewportView(jList1);

      jList2.setModel(new javax.swing.AbstractListModel() {
         String[] strings = taskManager.getTaskList(TaskStatus.DONE);
         public int getSize() { return strings.length; }
         public Object getElementAt(int i) { return strings[i]; }
      });
      jList2.addFocusListener(new java.awt.event.FocusAdapter() {
         public void focusGained(java.awt.event.FocusEvent evt) {
            jList2FocusGained(evt);
         }
      });
      jScrollPane2.setViewportView(jList2);

      jList3.setModel(new javax.swing.AbstractListModel() {
         String[] strings = taskManager.getTaskList(TaskStatus.TODO);
         public int getSize() { return strings.length; }
         public Object getElementAt(int i) { return strings[i]; }
      });
      jList3.addFocusListener(new java.awt.event.FocusAdapter() {
         public void focusGained(java.awt.event.FocusEvent evt) {
            jList3FocusGained(evt);
         }
      });
      jScrollPane3.setViewportView(jList3);

      jLabel1.setText("To-do:");

      jLabel2.setText("In progress:");

      jLabel3.setText("Done:");

      jMenu1.setText("Exit");
      jMenu1.addMenuListener(new javax.swing.event.MenuListener() {
         public void menuCanceled(javax.swing.event.MenuEvent evt) {
         }
         public void menuDeselected(javax.swing.event.MenuEvent evt) {
         }
         public void menuSelected(javax.swing.event.MenuEvent evt) {
            jMenu1MenuSelected(evt);
         }
      });
      jMenuBar1.add(jMenu1);

      jMenu2.setText("Add");
      jMenu2.addMenuListener(new javax.swing.event.MenuListener() {
         public void menuCanceled(javax.swing.event.MenuEvent evt) {
         }
         public void menuDeselected(javax.swing.event.MenuEvent evt) {
         }
         public void menuSelected(javax.swing.event.MenuEvent evt) {
            jMenu2MenuSelected(evt);
         }
      });
      jMenuBar1.add(jMenu2);

      jMenu3.setText("Edit");
      jMenu3.addMenuListener(new javax.swing.event.MenuListener() {
         public void menuCanceled(javax.swing.event.MenuEvent evt) {
         }
         public void menuDeselected(javax.swing.event.MenuEvent evt) {
         }
         public void menuSelected(javax.swing.event.MenuEvent evt) {
            jMenu3MenuSelected(evt);
         }
      });
      jMenuBar1.add(jMenu3);

      setJMenuBar(jMenuBar1);

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
               .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
               .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
               .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addContainerGap())
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel1)
               .addComponent(jLabel2)
               .addComponent(jLabel3))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
               .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
               .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE)))
      );

      pack();
      setLocationRelativeTo(null);
   }// </editor-fold>//GEN-END:initComponents

   private void jMenu1MenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu1MenuSelected
      System.exit(0); 
   }//GEN-LAST:event_jMenu1MenuSelected

   private void jMenu2MenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu2MenuSelected
      new AddTaskMenu(taskManager).setVisible(true);
      this.dispose();
   }//GEN-LAST:event_jMenu2MenuSelected

   private void jMenu3MenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu3MenuSelected
      JList selectedList = null;
      if (!jList3.isSelectionEmpty()) selectedList = jList3;
      else if (!jList1.isSelectionEmpty()) selectedList = jList1;
      else if (!jList2.isSelectionEmpty()) selectedList = jList2;

      if (selectedList == null) 
         JOptionPane.showMessageDialog(this, "Select an task to edit");
      else {
         new EditTaskMenu(taskManager, taskManager.getTask((String) selectedList.getSelectedValue())).setVisible(true);
         this.dispose();
      }
   }//GEN-LAST:event_jMenu3MenuSelected

   private void jList1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jList1FocusGained
      jList2.clearSelection();
      jList3.clearSelection();
   }//GEN-LAST:event_jList1FocusGained

   private void jList3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jList3FocusGained
      jList1.clearSelection();
      jList2.clearSelection();
   }//GEN-LAST:event_jList3FocusGained

   private void jList2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jList2FocusGained
      jList1.clearSelection();
      jList3.clearSelection();
   }//GEN-LAST:event_jList2FocusGained

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JLabel jLabel3;
   private javax.swing.JList jList1;
   private javax.swing.JList jList2;
   private javax.swing.JList jList3;
   private javax.swing.JMenu jMenu1;
   private javax.swing.JMenu jMenu2;
   private javax.swing.JMenu jMenu3;
   private javax.swing.JMenuBar jMenuBar1;
   private javax.swing.JScrollPane jScrollPane1;
   private javax.swing.JScrollPane jScrollPane2;
   private javax.swing.JScrollPane jScrollPane3;
   // End of variables declaration//GEN-END:variables
}
